### ISSUE TITLE
The optional query parameter "extras" must be escaped

### ISSUE THREAD

**Issue by mattiasbj** [wolfberry-ab/telldus-live-dotnet#10]
Some more stuff for ya,

Some of Telldus endpoints use an optional query parameter - "extras" - which is a comma-separated list of different commands. See for example in [ClientRepository.GetClientInfoAsync(...)](https://github.com/wolfberry-ab/telldus-live-dotnet/blob/e034d3953204b0af2392c2da931d16223e9363eb/Wolfberry.TelldusLive/Repositories/ClientRepository.cs#L31).

The problem is that since it is comma-separated, it must be escaped. `UrlBuilder.AddOptionalQuery(...)` doesn't do that. You need something similar to 

```
public void AddOptionalEscapedQuery(string name, string value)
{
    if (value != null)
    {
        AddAsEscapedQuery(name, value);
    }
}
```

I'm aware of this being a problem in

* `GetClientsAsync` in `ClientRepository`
* `GetDeviceInfoAsync` in `DeviceRepository`
* `GetDevicesAsync` in `DeviceRepository`

There might be more places though.

**Comment by the-mikael-johansson** [comment]
Thank you so much @mattiasbj for your awesome help!
