### ISSUE TITLE
Found a bug in DeviceRepository

### ISSUE THREAD

**Issue by ricwar** [wolfberry-ab/telldus-live-dotnet#3]
Hi!
Thanks for this excellent Telldus library, it really made my day when I found it! 😃 

However, I stumbled over a bug in the DeviceRepository.
Here is a link to the source code:

[DeviceRepository, line 59](https://github.com/wolfberry-ab/telldus-live-dotnet/blob/33f4c59eec11b3f4038e72ad13171ac393db0b7c/Wolfberry.TelldusLive/Repositories/DeviceRepository.cs#L59)

I'm guessing it is a copy-paste-error, the query should be 'method', not 'id'.
I am not using the device/command operation myself, I found this bug by accident and thought you might want to know about it.

Thanks!
Richard Warldén

**Comment by wolfberry-ab** [comment]
Hi Richard!

Thank you for reporting that bug. It's now fixed and released in version 2.0.1. 

Best regards,
Mikael Johansson
