### ISSUE TITLE
API url update

### ISSUE THREAD

**Issue by PatrikeN** [wolfberry-ab/telldus-live-dotnet#5]
I believe Telldus has changed the url to pa-api.telldus.com

https://telldus.com/driftinformation/

**Comment by the-mikael-johansson** [comment]
Hi @PatrikeN!

Thank you for notifying. I have released an updated NuGet (2.1.0) where it's possible to set a custom API URL. See example here: https://github.com/wolfberry-ab/telldus-live-dotnet/blob/main/Tests/ConsoleAppDotNet5/Program.cs

About the Telldus Live API: at the moment the pa-api.telldus.com seems to be down and the original api.telldus.com seems to work again.

Best regards,
Mikael
