### ISSUE TITLE
Query parameters wrong in SensorRepository.GetHistoryAsync

### ISSUE THREAD

**Issue by mattiasbj** [wolfberry-ab/telldus-live-dotnet#7]
Hello and thank you for an awesome Telldus client.

I have discovered a few issues. Easy fixes, but high impact.

[The query parameters for "from" and "to" are wrong in SensorRepository.GetHistoryAsync](https://github.com/wolfberry-ab/telldus-live-dotnet/blob/1e415cce8965113b9313d9d4f98554f16d297849/Wolfberry.TelldusLive/Repositories/SensorRepository.cs#L97). Should be just "from" and "to".

**Comment by wolfberry-ab** [comment]
Hi @mattiasbj!

Thank you for reporting this, I will look into it asap.

BR Mikael, Wolfberry

**Comment by wolfberry-ab** [comment]
The fix is now available as NuGet, https://www.nuget.org/packages/Wolfberry.TelldusLive/2.1.1.

BR Mikael
